const name = "Guilherme";
const birthCity = "Belo Horizonte";
let birthYear = 1988;
console.log(name);
console.log(birthCity);
console.log(birthYear);
birthYear = 2030;
console.log(birthYear);
// birthCity = "São Paulo";
console.log(birthCity);
